// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/agent/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// max_heartbeat_gap_blocks is the maximum number of blocks an agent can
	// go without a heartbeat before being auto-deactivated by EndBlock.
	// Default: 200. Set to 0 to disable auto-deactivation.
	MaxHeartbeatGapBlocks int64 `protobuf:"varint,1,opt,name=max_heartbeat_gap_blocks,json=maxHeartbeatGapBlocks,proto3" json:"max_heartbeat_gap_blocks,omitempty"`
	// max_actions_per_block is the maximum number of agent actions allowed
	// per agent per block. Default: 8.
	MaxActionsPerBlock uint64 `protobuf:"varint,2,opt,name=max_actions_per_block,json=maxActionsPerBlock,proto3" json:"max_actions_per_block,omitempty"`
	// min_heartbeat_interval_blocks is the minimum number of blocks between
	// heartbeats from the same agent. Default: 10.
	MinHeartbeatIntervalBlocks uint64 `protobuf:"varint,3,opt,name=min_heartbeat_interval_blocks,json=minHeartbeatIntervalBlocks,proto3" json:"min_heartbeat_interval_blocks,omitempty"`
	// max_intents_per_block is the maximum number of intents an agent can
	// submit per block. Default: 4.
	MaxIntentsPerBlock uint64 `protobuf:"varint,4,opt,name=max_intents_per_block,json=maxIntentsPerBlock,proto3" json:"max_intents_per_block,omitempty"`
	// max_tasks_per_block is the maximum number of tasks an agent can
	// delegate per block. Default: 4.
	MaxTasksPerBlock uint64 `protobuf:"varint,5,opt,name=max_tasks_per_block,json=maxTasksPerBlock,proto3" json:"max_tasks_per_block,omitempty"`
	// max_payload_bytes is the maximum size in bytes for free-form payload,
	// description, metadata, and requirements fields. Default: 4096.
	MaxPayloadBytes uint64 `protobuf:"varint,6,opt,name=max_payload_bytes,json=maxPayloadBytes,proto3" json:"max_payload_bytes,omitempty"`
	// min_agent_deposit_uclaw is the minimum deposit in uclaw required to
	// register an agent. Default: 1000000 (1 CLAW).
	MinAgentDepositUclaw uint64 `protobuf:"varint,7,opt,name=min_agent_deposit_uclaw,json=minAgentDepositUclaw,proto3" json:"min_agent_deposit_uclaw,omitempty"`
	// deposit_slash_per_penalty_bps is the basis points of deposit slashed
	// per SLA penalty event. Default: 100 (1%).
	DepositSlashPerPenaltyBps uint64 `protobuf:"varint,8,opt,name=deposit_slash_per_penalty_bps,json=depositSlashPerPenaltyBps,proto3" json:"deposit_slash_per_penalty_bps,omitempty"`
	// min_task_budget_uclaw is the minimum task delegation budget in uclaw.
	// Default: 1.
	MinTaskBudgetUclaw uint64 `protobuf:"varint,9,opt,name=min_task_budget_uclaw,json=minTaskBudgetUclaw,proto3" json:"min_task_budget_uclaw,omitempty"`
	// high_impact_min_deposit_uclaw is the minimum locked agent deposit
	// required to execute high-impact actions (e.g. transfer/coordinate).
	HighImpactMinDepositUclaw uint64 `protobuf:"varint,10,opt,name=high_impact_min_deposit_uclaw,json=highImpactMinDepositUclaw,proto3" json:"high_impact_min_deposit_uclaw,omitempty"`
	// standard_task_min_budget_uclaw is the minimum budget required for
	// deadline-bound (non-expedited) delegated tasks.
	StandardTaskMinBudgetUclaw uint64 `protobuf:"varint,11,opt,name=standard_task_min_budget_uclaw,json=standardTaskMinBudgetUclaw,proto3" json:"standard_task_min_budget_uclaw,omitempty"`
	// expedited_task_min_budget_uclaw is the minimum budget required for
	// short-deadline delegated tasks (higher quality tier).
	ExpeditedTaskMinBudgetUclaw uint64 `protobuf:"varint,12,opt,name=expedited_task_min_budget_uclaw,json=expeditedTaskMinBudgetUclaw,proto3" json:"expedited_task_min_budget_uclaw,omitempty"`
	// expedited_task_max_deadline_blocks defines the max deadline window
	// (in blocks) for a task to be classified as expedited quality tier.
	ExpeditedTaskMaxDeadlineBlocks uint64 `protobuf:"varint,13,opt,name=expedited_task_max_deadline_blocks,json=expeditedTaskMaxDeadlineBlocks,proto3" json:"expedited_task_max_deadline_blocks,omitempty"`
	// agent_reward_pool_fraction_bps is the fraction of inflation directed
	// to the agent reward pool, in basis points. Default: 1000 (10%).
	AgentRewardPoolFractionBps uint64 `protobuf:"varint,14,opt,name=agent_reward_pool_fraction_bps,json=agentRewardPoolFractionBps,proto3" json:"agent_reward_pool_fraction_bps,omitempty"`
	// min_reputation_for_reward_bps is the minimum reputation score (in bps
	// of max) an agent must hold to be eligible for rewards. Default: 5000 (50%).
	MinReputationForRewardBps uint64 `protobuf:"varint,15,opt,name=min_reputation_for_reward_bps,json=minReputationForRewardBps,proto3" json:"min_reputation_for_reward_bps,omitempty"`
	// reward_distribution_interval_blocks is how often (in blocks) the agent
	// reward pool is distributed. Default: 100.
	RewardDistributionIntervalBlocks uint64 `protobuf:"varint,16,opt,name=reward_distribution_interval_blocks,json=rewardDistributionIntervalBlocks,proto3" json:"reward_distribution_interval_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb4ac75308fa7c18, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxHeartbeatGapBlocks() int64 {
	if m != nil {
		return m.MaxHeartbeatGapBlocks
	}
	return 0
}

func (m *Params) GetMaxActionsPerBlock() uint64 {
	if m != nil {
		return m.MaxActionsPerBlock
	}
	return 0
}

func (m *Params) GetMinHeartbeatIntervalBlocks() uint64 {
	if m != nil {
		return m.MinHeartbeatIntervalBlocks
	}
	return 0
}

func (m *Params) GetMaxIntentsPerBlock() uint64 {
	if m != nil {
		return m.MaxIntentsPerBlock
	}
	return 0
}

func (m *Params) GetMaxTasksPerBlock() uint64 {
	if m != nil {
		return m.MaxTasksPerBlock
	}
	return 0
}

func (m *Params) GetMaxPayloadBytes() uint64 {
	if m != nil {
		return m.MaxPayloadBytes
	}
	return 0
}

func (m *Params) GetMinAgentDepositUclaw() uint64 {
	if m != nil {
		return m.MinAgentDepositUclaw
	}
	return 0
}

func (m *Params) GetDepositSlashPerPenaltyBps() uint64 {
	if m != nil {
		return m.DepositSlashPerPenaltyBps
	}
	return 0
}

func (m *Params) GetMinTaskBudgetUclaw() uint64 {
	if m != nil {
		return m.MinTaskBudgetUclaw
	}
	return 0
}

func (m *Params) GetHighImpactMinDepositUclaw() uint64 {
	if m != nil {
		return m.HighImpactMinDepositUclaw
	}
	return 0
}

func (m *Params) GetStandardTaskMinBudgetUclaw() uint64 {
	if m != nil {
		return m.StandardTaskMinBudgetUclaw
	}
	return 0
}

func (m *Params) GetExpeditedTaskMinBudgetUclaw() uint64 {
	if m != nil {
		return m.ExpeditedTaskMinBudgetUclaw
	}
	return 0
}

func (m *Params) GetExpeditedTaskMaxDeadlineBlocks() uint64 {
	if m != nil {
		return m.ExpeditedTaskMaxDeadlineBlocks
	}
	return 0
}

func (m *Params) GetAgentRewardPoolFractionBps() uint64 {
	if m != nil {
		return m.AgentRewardPoolFractionBps
	}
	return 0
}

func (m *Params) GetMinReputationForRewardBps() uint64 {
	if m != nil {
		return m.MinReputationForRewardBps
	}
	return 0
}

func (m *Params) GetRewardDistributionIntervalBlocks() uint64 {
	if m != nil {
		return m.RewardDistributionIntervalBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "clawchain.agent.v1.Params")
}

func init() { proto.RegisterFile("clawchain/agent/v1/params.proto", fileDescriptor_fb4ac75308fa7c18) }

var fileDescriptor_fb4ac75308fa7c18 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x1b, 0x36, 0x0a, 0x18, 0x10, 0x2c, 0x0c, 0x2d, 0x14, 0x2d, 0x1d, 0x3b, 0x4d, 0x93,
	0x68, 0x55, 0x21, 0x84, 0xc4, 0x89, 0x46, 0x95, 0xa0, 0x48, 0x93, 0xa2, 0x01, 0x17, 0x2e, 0xd6,
	0x3f, 0x89, 0x95, 0x58, 0x8b, 0x1d, 0x2b, 0xf6, 0x4a, 0xfa, 0x0a, 0x9c, 0x78, 0x04, 0x1e, 0x80,
	0x03, 0x8f, 0xc1, 0x71, 0x47, 0x8e, 0xa8, 0x3d, 0xc0, 0x63, 0x20, 0xdb, 0x49, 0x68, 0x80, 0x5d,
	0xa2, 0xc8, 0xdf, 0xef, 0xfb, 0xbe, 0xbf, 0xe3, 0x18, 0x0d, 0xe3, 0x1c, 0x3e, 0xc4, 0x19, 0x50,
	0x3e, 0x86, 0x94, 0x70, 0x35, 0x5e, 0x4c, 0xc6, 0x02, 0x4a, 0x60, 0x72, 0x24, 0xca, 0x42, 0x15,
	0xae, 0xdb, 0x02, 0x23, 0x03, 0x8c, 0x16, 0x93, 0xc1, 0x0e, 0x30, 0xca, 0x8b, 0xb1, 0x79, 0x5a,
	0x6c, 0xb0, 0x9b, 0x16, 0x69, 0x61, 0x5e, 0xc7, 0xfa, 0xcd, 0xae, 0x1e, 0x7e, 0xe9, 0xa3, 0x7e,
	0x68, 0xd2, 0xdc, 0x67, 0xc8, 0x63, 0x50, 0xe1, 0x8c, 0x40, 0xa9, 0x22, 0x02, 0x0a, 0xa7, 0x20,
	0x70, 0x94, 0x17, 0xf1, 0x99, 0xf4, 0x9c, 0x03, 0xe7, 0x68, 0xeb, 0xf4, 0x3e, 0x83, 0xea, 0x55,
	0x23, 0xbf, 0x04, 0x11, 0x18, 0xd1, 0x9d, 0x20, 0x2d, 0x60, 0x88, 0x15, 0x2d, 0xb8, 0xc4, 0x82,
	0x94, 0xd6, 0xe6, 0x5d, 0x39, 0x70, 0x8e, 0xb6, 0x4f, 0x5d, 0x06, 0xd5, 0xd4, 0x6a, 0x21, 0x29,
	0x8d, 0xc7, 0x9d, 0xa2, 0x7d, 0x46, 0xf9, 0x46, 0x17, 0xe5, 0x8a, 0x94, 0x0b, 0xc8, 0x9b, 0xc2,
	0x2d, 0x63, 0x1d, 0x30, 0xca, 0xdb, 0xc2, 0x79, 0x8d, 0x74, 0x5b, 0xb5, 0x91, 0xab, 0xcd, 0xd6,
	0xed, 0xb6, 0x75, 0x6e, 0xb5, 0xb6, 0xf5, 0x31, 0xba, 0xa7, 0x2d, 0x0a, 0xe4, 0xd9, 0xa6, 0xe1,
	0xaa, 0x31, 0xdc, 0x65, 0x50, 0xbd, 0xd5, 0x4a, 0x8b, 0x1f, 0xa3, 0x1d, 0x8d, 0x0b, 0x58, 0xe6,
	0x05, 0x24, 0x38, 0x5a, 0x2a, 0x22, 0xbd, 0xbe, 0x81, 0xef, 0x30, 0xa8, 0x42, 0xbb, 0x1e, 0xe8,
	0x65, 0xf7, 0x29, 0xda, 0xd3, 0x1b, 0x32, 0x07, 0x80, 0x13, 0x22, 0x0a, 0x49, 0x15, 0x3e, 0xd7,
	0x27, 0xe3, 0x5d, 0x33, 0x8e, 0x5d, 0x46, 0xf9, 0x54, 0xab, 0x33, 0x2b, 0xbe, 0xd3, 0x9a, 0xfb,
	0x02, 0xed, 0x37, 0xb0, 0xcc, 0x41, 0x66, 0x66, 0x2a, 0x41, 0x38, 0xe4, 0x6a, 0x89, 0x23, 0x21,
	0xbd, 0xeb, 0xc6, 0xfc, 0xa0, 0x86, 0xde, 0x68, 0x26, 0x24, 0x65, 0x68, 0x89, 0x40, 0xd8, 0xcf,
	0x40, 0xb9, 0xd9, 0x13, 0x8e, 0xce, 0x93, 0x94, 0x34, 0xb5, 0x37, 0xea, 0xcf, 0x40, 0xb9, 0xde,
	0x55, 0x60, 0xa4, 0xb6, 0x34, 0xa3, 0x69, 0x86, 0x29, 0x13, 0x10, 0x2b, 0xac, 0xed, 0xdd, 0x89,
	0x91, 0x2d, 0xd5, 0xd0, 0xdc, 0x30, 0x27, 0x94, 0x77, 0xc6, 0x0e, 0x90, 0x2f, 0x15, 0xf0, 0x04,
	0xca, 0xc4, 0x36, 0xeb, 0x8c, 0x4e, 0xfb, 0x4d, 0x7b, 0x7e, 0x0d, 0xa5, 0x47, 0x38, 0xa1, 0x7c,
	0x73, 0x8a, 0x19, 0x1a, 0x92, 0x4a, 0x90, 0x84, 0x2a, 0x72, 0x59, 0xc8, 0x2d, 0x13, 0xf2, 0xb0,
	0xc5, 0xfe, 0x93, 0xf2, 0x1a, 0x1d, 0xfe, 0x9d, 0x02, 0x15, 0x4e, 0x08, 0x24, 0x39, 0xe5, 0xa4,
	0xf9, 0x9b, 0x6e, 0x9b, 0x20, 0xbf, 0x1b, 0x04, 0xd5, 0xac, 0xc6, 0xec, 0x1f, 0xf5, 0xfc, 0xd1,
	0xaf, 0xcf, 0x43, 0xe7, 0xe3, 0xcf, 0xaf, 0xc7, 0xde, 0x9f, 0x2b, 0x57, 0xd5, 0x97, 0xce, 0xde,
	0x91, 0x60, 0xf2, 0x6d, 0xe5, 0x3b, 0x17, 0x2b, 0xdf, 0xf9, 0xb1, 0xf2, 0x9d, 0x4f, 0x6b, 0xbf,
	0x77, 0xb1, 0xf6, 0x7b, 0xdf, 0xd7, 0x7e, 0xef, 0xfd, 0xde, 0xbf, 0x1e, 0xb5, 0x14, 0x44, 0x46,
	0x7d, 0x73, 0xd1, 0x9e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x32, 0xfa, 0x62, 0xc8, 0x03,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxHeartbeatGapBlocks != that1.MaxHeartbeatGapBlocks {
		return false
	}
	if this.MaxActionsPerBlock != that1.MaxActionsPerBlock {
		return false
	}
	if this.MinHeartbeatIntervalBlocks != that1.MinHeartbeatIntervalBlocks {
		return false
	}
	if this.MaxIntentsPerBlock != that1.MaxIntentsPerBlock {
		return false
	}
	if this.MaxTasksPerBlock != that1.MaxTasksPerBlock {
		return false
	}
	if this.MaxPayloadBytes != that1.MaxPayloadBytes {
		return false
	}
	if this.MinAgentDepositUclaw != that1.MinAgentDepositUclaw {
		return false
	}
	if this.DepositSlashPerPenaltyBps != that1.DepositSlashPerPenaltyBps {
		return false
	}
	if this.MinTaskBudgetUclaw != that1.MinTaskBudgetUclaw {
		return false
	}
	if this.HighImpactMinDepositUclaw != that1.HighImpactMinDepositUclaw {
		return false
	}
	if this.StandardTaskMinBudgetUclaw != that1.StandardTaskMinBudgetUclaw {
		return false
	}
	if this.ExpeditedTaskMinBudgetUclaw != that1.ExpeditedTaskMinBudgetUclaw {
		return false
	}
	if this.ExpeditedTaskMaxDeadlineBlocks != that1.ExpeditedTaskMaxDeadlineBlocks {
		return false
	}
	if this.AgentRewardPoolFractionBps != that1.AgentRewardPoolFractionBps {
		return false
	}
	if this.MinReputationForRewardBps != that1.MinReputationForRewardBps {
		return false
	}
	if this.RewardDistributionIntervalBlocks != that1.RewardDistributionIntervalBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardDistributionIntervalBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RewardDistributionIntervalBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.MinReputationForRewardBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinReputationForRewardBps))
		i--
		dAtA[i] = 0x78
	}
	if m.AgentRewardPoolFractionBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AgentRewardPoolFractionBps))
		i--
		dAtA[i] = 0x70
	}
	if m.ExpeditedTaskMaxDeadlineBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ExpeditedTaskMaxDeadlineBlocks))
		i--
		dAtA[i] = 0x68
	}
	if m.ExpeditedTaskMinBudgetUclaw != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ExpeditedTaskMinBudgetUclaw))
		i--
		dAtA[i] = 0x60
	}
	if m.StandardTaskMinBudgetUclaw != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StandardTaskMinBudgetUclaw))
		i--
		dAtA[i] = 0x58
	}
	if m.HighImpactMinDepositUclaw != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HighImpactMinDepositUclaw))
		i--
		dAtA[i] = 0x50
	}
	if m.MinTaskBudgetUclaw != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinTaskBudgetUclaw))
		i--
		dAtA[i] = 0x48
	}
	if m.DepositSlashPerPenaltyBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DepositSlashPerPenaltyBps))
		i--
		dAtA[i] = 0x40
	}
	if m.MinAgentDepositUclaw != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinAgentDepositUclaw))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxPayloadBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPayloadBytes))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxTasksPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTasksPerBlock))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxIntentsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxIntentsPerBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.MinHeartbeatIntervalBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinHeartbeatIntervalBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxActionsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxActionsPerBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxHeartbeatGapBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxHeartbeatGapBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxHeartbeatGapBlocks != 0 {
		n += 1 + sovParams(uint64(m.MaxHeartbeatGapBlocks))
	}
	if m.MaxActionsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxActionsPerBlock))
	}
	if m.MinHeartbeatIntervalBlocks != 0 {
		n += 1 + sovParams(uint64(m.MinHeartbeatIntervalBlocks))
	}
	if m.MaxIntentsPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxIntentsPerBlock))
	}
	if m.MaxTasksPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxTasksPerBlock))
	}
	if m.MaxPayloadBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxPayloadBytes))
	}
	if m.MinAgentDepositUclaw != 0 {
		n += 1 + sovParams(uint64(m.MinAgentDepositUclaw))
	}
	if m.DepositSlashPerPenaltyBps != 0 {
		n += 1 + sovParams(uint64(m.DepositSlashPerPenaltyBps))
	}
	if m.MinTaskBudgetUclaw != 0 {
		n += 1 + sovParams(uint64(m.MinTaskBudgetUclaw))
	}
	if m.HighImpactMinDepositUclaw != 0 {
		n += 1 + sovParams(uint64(m.HighImpactMinDepositUclaw))
	}
	if m.StandardTaskMinBudgetUclaw != 0 {
		n += 1 + sovParams(uint64(m.StandardTaskMinBudgetUclaw))
	}
	if m.ExpeditedTaskMinBudgetUclaw != 0 {
		n += 1 + sovParams(uint64(m.ExpeditedTaskMinBudgetUclaw))
	}
	if m.ExpeditedTaskMaxDeadlineBlocks != 0 {
		n += 1 + sovParams(uint64(m.ExpeditedTaskMaxDeadlineBlocks))
	}
	if m.AgentRewardPoolFractionBps != 0 {
		n += 1 + sovParams(uint64(m.AgentRewardPoolFractionBps))
	}
	if m.MinReputationForRewardBps != 0 {
		n += 1 + sovParams(uint64(m.MinReputationForRewardBps))
	}
	if m.RewardDistributionIntervalBlocks != 0 {
		n += 2 + sovParams(uint64(m.RewardDistributionIntervalBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxHeartbeatGapBlocks", wireType)
			}
			m.MaxHeartbeatGapBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxHeartbeatGapBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActionsPerBlock", wireType)
			}
			m.MaxActionsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActionsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinHeartbeatIntervalBlocks", wireType)
			}
			m.MinHeartbeatIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinHeartbeatIntervalBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIntentsPerBlock", wireType)
			}
			m.MaxIntentsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxIntentsPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTasksPerBlock", wireType)
			}
			m.MaxTasksPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTasksPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPayloadBytes", wireType)
			}
			m.MaxPayloadBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPayloadBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAgentDepositUclaw", wireType)
			}
			m.MinAgentDepositUclaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAgentDepositUclaw |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositSlashPerPenaltyBps", wireType)
			}
			m.DepositSlashPerPenaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositSlashPerPenaltyBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTaskBudgetUclaw", wireType)
			}
			m.MinTaskBudgetUclaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinTaskBudgetUclaw |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighImpactMinDepositUclaw", wireType)
			}
			m.HighImpactMinDepositUclaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HighImpactMinDepositUclaw |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StandardTaskMinBudgetUclaw", wireType)
			}
			m.StandardTaskMinBudgetUclaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StandardTaskMinBudgetUclaw |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpeditedTaskMinBudgetUclaw", wireType)
			}
			m.ExpeditedTaskMinBudgetUclaw = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpeditedTaskMinBudgetUclaw |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpeditedTaskMaxDeadlineBlocks", wireType)
			}
			m.ExpeditedTaskMaxDeadlineBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpeditedTaskMaxDeadlineBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentRewardPoolFractionBps", wireType)
			}
			m.AgentRewardPoolFractionBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentRewardPoolFractionBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReputationForRewardBps", wireType)
			}
			m.MinReputationForRewardBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinReputationForRewardBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDistributionIntervalBlocks", wireType)
			}
			m.RewardDistributionIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardDistributionIntervalBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
