/**
 * `clawd deploy-profile` — generate deployment configuration for different targets.
 *
 * Targets: local, vps, docker, k8s
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type DeployProfileOptions = {
  target: "local" | "vps" | "k8s" | "docker";
  output?: string;
  json?: boolean;
  moniker?: string;
  chainId?: string;
  rpcPort?: string;
  restPort?: string;
};

type ProfileResult = {
  target: string;
  files: { name: string; content: string }[];
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function defaults(opts: DeployProfileOptions) {
  return {
    moniker: opts.moniker ?? "clawchain-node",
    chainId: opts.chainId ?? "clawchain-1",
    rpcPort: opts.rpcPort ?? "26657",
    restPort: opts.restPort ?? "1317",
  };
}

// ---------------------------------------------------------------------------
// Local profile
// ---------------------------------------------------------------------------

function generateLocal(opts: DeployProfileOptions): ProfileResult {
  const d = defaults(opts);

  const config = JSON.stringify(
    {
      chainId: d.chainId,
      rpcUrl: `http://localhost:${d.rpcPort}`,
      restUrl: `http://localhost:${d.restPort}`,
      nodeAutoStart: true,
      nodeHome: "",
      moniker: d.moniker,
      denom: "uclaw",
      prefix: "claw",
      gasPrice: "0.025uclaw",
    },
    null,
    2,
  );

  const script = `#!/bin/bash
# ClawChain Local Provider Setup
# Generated by: clawd deploy-profile --target local
set -euo pipefail

echo "Starting ClawChain local environment..."
echo "  Moniker:  ${d.moniker}"
echo "  Chain ID: ${d.chainId}"
echo "  RPC:      http://localhost:${d.rpcPort}"
echo "  REST:     http://localhost:${d.restPort}"

# Start the chain node in the background
clawchaind start --home ~/.clawchain \\
  --rpc.laddr tcp://0.0.0.0:${d.rpcPort} \\
  --api.address tcp://0.0.0.0:${d.restPort} &
CHAIN_PID=$!

# Wait for the chain to become healthy
echo "Waiting for chain node..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:${d.rpcPort}/health > /dev/null 2>&1; then
    echo "Chain node is healthy."
    break
  fi
  sleep 2
done

# Start clawd
clawd up

# Cleanup on exit
trap "kill $CHAIN_PID 2>/dev/null" EXIT
wait $CHAIN_PID
`;

  return {
    target: "local",
    files: [
      { name: "clawd.json", content: config },
      { name: "start-local.sh", content: script },
    ],
  };
}

// ---------------------------------------------------------------------------
// VPS profile
// ---------------------------------------------------------------------------

function generateVps(opts: DeployProfileOptions): ProfileResult {
  const d = defaults(opts);

  const clawchaindService = `[Unit]
Description=ClawChain Validator Node
Documentation=https://github.com/clawchain/clawchain
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=clawchain
Group=clawchain
ExecStart=/usr/local/bin/clawchaind start --home /var/lib/clawchain/.clawchain
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=10
StartLimitInterval=200
StartLimitBurst=5

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=clawchaind

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/clawchain

# Resource limits
LimitNOFILE=65535
LimitNPROC=4096
MemoryMax=8G
CPUQuota=400%

# Environment
Environment="HOME=/var/lib/clawchain"
Environment="CHAIN_ID=${d.chainId}"
Environment="MONIKER=${d.moniker}"

[Install]
WantedBy=multi-user.target
`;

  const clawdService = `[Unit]
Description=ClawChain CLI Daemon (clawd)
Documentation=https://github.com/clawchain/clawchain
After=network-online.target clawchaind.service
Wants=network-online.target

[Service]
Type=simple
User=clawchain
Group=clawchain
ExecStart=/usr/bin/node /opt/clawd/dist/main.js up
Restart=on-failure
RestartSec=10
StartLimitInterval=200
StartLimitBurst=5

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=clawd

# Environment
Environment="BLOCKCHAIN_RPC_URL=http://localhost:${d.rpcPort}"
Environment="BLOCKCHAIN_REST_URL=http://localhost:${d.restPort}"
Environment="BLOCKCHAIN_CHAIN_ID=${d.chainId}"
EnvironmentFile=-/etc/clawchain/clawd.env

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/clawchain

# Resource limits
LimitNOFILE=4096
MemoryMax=1G

[Install]
WantedBy=multi-user.target
`;

  const nginxConf = `# ClawChain Nginx Configuration
# Generated by: clawd deploy-profile --target vps

upstream clawchain_rpc {
    server 127.0.0.1:${d.rpcPort};
}

upstream clawchain_rest {
    server 127.0.0.1:${d.restPort};
}

upstream clawchain_grpc {
    server 127.0.0.1:9090;
}

server {
    listen 80;
    server_name _;

    # RPC endpoint
    location /rpc/ {
        proxy_pass http://clawchain_rpc/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # REST/LCD endpoint
    location /api/ {
        proxy_pass http://clawchain_rest/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSocket for CometBFT
    location /websocket {
        proxy_pass http://clawchain_rpc/websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Health check
    location /health {
        proxy_pass http://clawchain_rpc/health;
    }

    # TLS placeholder — replace with your certificate paths
    # listen 443 ssl;
    # ssl_certificate /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem;
}
`;

  const firewallRules = `#!/bin/bash
# ClawChain UFW Firewall Rules
# Generated by: clawd deploy-profile --target vps
set -euo pipefail

echo "Configuring firewall rules for ClawChain VPS..."

# Reset UFW (optional — uncomment if you want a clean slate)
# ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# SSH (always allow)
ufw allow 22/tcp comment "SSH"

# CometBFT P2P (required for peer connections)
ufw allow 26656/tcp comment "CometBFT P2P"

# CometBFT RPC (optional — expose only if needed externally)
ufw allow ${d.rpcPort}/tcp comment "CometBFT RPC"

# REST/LCD API (optional — expose only if needed externally)
ufw allow ${d.restPort}/tcp comment "REST API"

# gRPC (optional — expose only if needed externally)
ufw allow 9090/tcp comment "gRPC"

# HTTP/HTTPS for Nginx
ufw allow 80/tcp comment "HTTP"
ufw allow 443/tcp comment "HTTPS"

# Enable UFW
ufw --force enable

echo "Firewall configured. Active rules:"
ufw status verbose
`;

  return {
    target: "vps",
    files: [
      { name: "clawchaind.service", content: clawchaindService },
      { name: "clawd.service", content: clawdService },
      { name: "nginx-clawchain.conf", content: nginxConf },
      { name: "setup-firewall.sh", content: firewallRules },
    ],
  };
}

// ---------------------------------------------------------------------------
// Docker profile
// ---------------------------------------------------------------------------

function generateDocker(opts: DeployProfileOptions): ProfileResult {
  const d = defaults(opts);

  const compose = `##
## ClawChain Docker Compose — Essential Services
## Generated by: clawd deploy-profile --target docker
##
## Usage:
##   docker compose -f docker-compose.clawchain.yml up -d
##   docker compose -f docker-compose.clawchain.yml logs -f clawchain
##   docker compose -f docker-compose.clawchain.yml down
##

services:
  # -- ClawChain Node --------------------------------------------------------
  clawchain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clawchain-node
    ports:
      - "${d.rpcPort}:26657"    # CometBFT RPC
      - "${d.restPort}:1317"    # REST API
      - "9090:9090"             # gRPC
      - "26660:26660"           # Prometheus metrics
    volumes:
      - clawchain-data:/root/.clawchain
    environment:
      - CHAIN_ID=${d.chainId}
      - MONIKER=${d.moniker}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s
    networks:
      - clawnet
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "4.0"
        reservations:
          memory: 2G
          cpus: "1.0"

  # -- clawd Agent -----------------------------------------------------------
  clawd:
    build:
      context: ./cmd/clawd
      dockerfile: Dockerfile
    container_name: clawchain-clawd
    environment:
      - BLOCKCHAIN_RPC_URL=http://clawchain:26657
      - BLOCKCHAIN_REST_URL=http://clawchain:1317
      - BLOCKCHAIN_CHAIN_ID=${d.chainId}
      - BLOCKCHAIN_AUTONOMOUS_LOOP_ENABLED=true
    depends_on:
      clawchain:
        condition: service_healthy
    networks:
      - clawnet
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  # -- Token Faucet ----------------------------------------------------------
  claw-faucet:
    build:
      context: .
      dockerfile: cmd/claw-faucet/Dockerfile
    container_name: clawchain-faucet
    ports:
      - "8888:8888"
    environment:
      - CHAIN_REST=http://clawchain:1317
      - CHAIN_RPC=http://clawchain:26657
      - CHAIN_ID=${d.chainId}
      - FAUCET_MNEMONIC=REPLACE_WITH_FAUCET_MNEMONIC
      - FAUCET_AMOUNT=10000000
    depends_on:
      clawchain:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - clawnet
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

networks:
  clawnet:
    driver: bridge

volumes:
  clawchain-data:
`;

  return {
    target: "docker",
    files: [
      { name: "docker-compose.clawchain.yml", content: compose },
    ],
  };
}

// ---------------------------------------------------------------------------
// K8s profile
// ---------------------------------------------------------------------------

function generateK8s(opts: DeployProfileOptions): ProfileResult {
  const d = defaults(opts);

  const namespace = `apiVersion: v1
kind: Namespace
metadata:
  name: clawchain
  labels:
    app.kubernetes.io/part-of: clawchain
    app.kubernetes.io/managed-by: clawd
`;

  const configmap = `apiVersion: v1
kind: ConfigMap
metadata:
  name: clawchain-config
  namespace: clawchain
  labels:
    app.kubernetes.io/part-of: clawchain
data:
  CHAIN_ID: "${d.chainId}"
  MONIKER: "${d.moniker}"
  RPC_PORT: "${d.rpcPort}"
  REST_PORT: "${d.restPort}"
  GRPC_PORT: "9090"
  P2P_PORT: "26656"
  PROMETHEUS_PORT: "26660"
`;

  const deployment = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: clawchain-node
  namespace: clawchain
  labels:
    app: clawchain-node
    app.kubernetes.io/part-of: clawchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clawchain-node
  template:
    metadata:
      labels:
        app: clawchain-node
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: clawchaind
          image: clawchain/clawchaind:latest
          ports:
            - containerPort: 26657
              name: rpc
            - containerPort: 1317
              name: rest
            - containerPort: 9090
              name: grpc
            - containerPort: 26656
              name: p2p
            - containerPort: 26660
              name: metrics
          envFrom:
            - configMapRef:
                name: clawchain-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 26657
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 26657
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          volumeMounts:
            - name: chain-data
              mountPath: /root/.clawchain
      volumes:
        - name: chain-data
          persistentVolumeClaim:
            claimName: clawchain-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawchain-data
  namespace: clawchain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
`;

  const service = `apiVersion: v1
kind: Service
metadata:
  name: clawchain-node
  namespace: clawchain
  labels:
    app: clawchain-node
    app.kubernetes.io/part-of: clawchain
spec:
  selector:
    app: clawchain-node
  ports:
    - name: rpc
      port: ${d.rpcPort}
      targetPort: 26657
      protocol: TCP
    - name: rest
      port: ${d.restPort}
      targetPort: 1317
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: p2p
      port: 26656
      targetPort: 26656
      protocol: TCP
    - name: metrics
      port: 26660
      targetPort: 26660
      protocol: TCP
  type: ClusterIP
`;

  return {
    target: "k8s",
    files: [
      { name: "namespace.yaml", content: namespace },
      { name: "configmap.yaml", content: configmap },
      { name: "deployment.yaml", content: deployment },
      { name: "service.yaml", content: service },
    ],
  };
}

// ---------------------------------------------------------------------------
// Profile dispatch
// ---------------------------------------------------------------------------

const generators: Record<string, (opts: DeployProfileOptions) => ProfileResult> = {
  local: generateLocal,
  vps: generateVps,
  docker: generateDocker,
  k8s: generateK8s,
};

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export async function runDeployProfile(opts: DeployProfileOptions): Promise<void> {
  const gen = generators[opts.target];
  if (!gen) {
    console.error(`Unknown target: ${opts.target}. Valid targets: local, vps, docker, k8s`);
    process.exitCode = 1;
    return;
  }

  const result = gen(opts);

  // JSON mode — emit the entire result as structured JSON
  if (opts.json) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    return;
  }

  // Output to directory
  if (opts.output) {
    mkdirSync(opts.output, { recursive: true });
    for (const file of result.files) {
      const filePath = join(opts.output, file.name);
      writeFileSync(filePath, file.content);
      console.log(`  wrote ${filePath}`);
    }
    console.log(`\nDeploy profile "${opts.target}" written to ${opts.output}/`);
    return;
  }

  // Default: print to stdout
  for (const file of result.files) {
    console.log(`# --- ${file.name} ---`);
    console.log(file.content);
  }
}
