// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/reputation/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MaxCommentLength uint64 `protobuf:"varint,1,opt,name=max_comment_length,json=maxCommentLength,proto3" json:"max_comment_length,omitempty"`
	// Reputation uptime score penalty (bps) when an agent becomes stale.
	HeartbeatPenaltyBps uint64 `protobuf:"varint,2,opt,name=heartbeat_penalty_bps,json=heartbeatPenaltyBps,proto3" json:"heartbeat_penalty_bps,omitempty"`
	// Reputation uptime score recovery reward (bps) when an agent recovers.
	HeartbeatRecoveryBps uint64 `protobuf:"varint,3,opt,name=heartbeat_recovery_bps,json=heartbeatRecoveryBps,proto3" json:"heartbeat_recovery_bps,omitempty"`
	// Task-SLA on-time reward (bps) applied when a completed task meets deadline.
	TaskSlaOnTimeRewardBps uint64 `protobuf:"varint,4,opt,name=task_sla_on_time_reward_bps,json=taskSlaOnTimeRewardBps,proto3" json:"task_sla_on_time_reward_bps,omitempty"`
	// Task-SLA late penalty (bps) per lateness step when a task misses deadline.
	TaskSlaLatePenaltyBps uint64 `protobuf:"varint,5,opt,name=task_sla_late_penalty_bps,json=taskSlaLatePenaltyBps,proto3" json:"task_sla_late_penalty_bps,omitempty"`
	// Number of blocks per lateness step for task SLA penalties.
	TaskSlaLatenessStepBlocks uint64 `protobuf:"varint,6,opt,name=task_sla_lateness_step_blocks,json=taskSlaLatenessStepBlocks,proto3" json:"task_sla_lateness_step_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6438c90ebfb9f6b9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxCommentLength() uint64 {
	if m != nil {
		return m.MaxCommentLength
	}
	return 0
}

func (m *Params) GetHeartbeatPenaltyBps() uint64 {
	if m != nil {
		return m.HeartbeatPenaltyBps
	}
	return 0
}

func (m *Params) GetHeartbeatRecoveryBps() uint64 {
	if m != nil {
		return m.HeartbeatRecoveryBps
	}
	return 0
}

func (m *Params) GetTaskSlaOnTimeRewardBps() uint64 {
	if m != nil {
		return m.TaskSlaOnTimeRewardBps
	}
	return 0
}

func (m *Params) GetTaskSlaLatePenaltyBps() uint64 {
	if m != nil {
		return m.TaskSlaLatePenaltyBps
	}
	return 0
}

func (m *Params) GetTaskSlaLatenessStepBlocks() uint64 {
	if m != nil {
		return m.TaskSlaLatenessStepBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "clawchain.reputation.v1.Params")
}

func init() {
	proto.RegisterFile("clawchain/reputation/v1/params.proto", fileDescriptor_6438c90ebfb9f6b9)
}

var fileDescriptor_6438c90ebfb9f6b9 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd1, 0x3d, 0x6f, 0xda, 0x40,
	0x18, 0x07, 0x70, 0xbb, 0x50, 0x86, 0x9b, 0x5a, 0x17, 0x28, 0xd0, 0x62, 0x55, 0x55, 0xa5, 0x56,
	0xa8, 0xc2, 0xa2, 0xad, 0xaa, 0x28, 0x59, 0x22, 0xb2, 0x22, 0x05, 0x41, 0xa6, 0x2c, 0xa7, 0xc7,
	0xce, 0x23, 0xb0, 0xf0, 0xbd, 0xe8, 0xee, 0xc2, 0xcb, 0x9a, 0x31, 0x53, 0x94, 0x4f, 0xc2, 0xc7,
	0xc8, 0xc8, 0x98, 0x31, 0x82, 0x81, 0xaf, 0x11, 0xf9, 0x8c, 0x0c, 0x0c, 0x59, 0xac, 0xd3, 0xfd,
	0xff, 0x3f, 0xeb, 0xd1, 0x3d, 0xe4, 0x47, 0x94, 0xc0, 0x2c, 0x1a, 0x43, 0xcc, 0x03, 0x85, 0xf2,
	0xd6, 0x80, 0x89, 0x05, 0x0f, 0xa6, 0x9d, 0x40, 0x82, 0x02, 0xa6, 0xdb, 0x52, 0x09, 0x23, 0xbc,
	0xcf, 0x79, 0xab, 0xbd, 0x6f, 0xb5, 0xa7, 0x9d, 0xc6, 0x47, 0x60, 0x31, 0x17, 0x81, 0xfd, 0x66,
	0xdd, 0x46, 0x79, 0x24, 0x46, 0xc2, 0x1e, 0x83, 0xf4, 0x94, 0xdd, 0x7e, 0xbf, 0x2b, 0x90, 0x52,
	0xdf, 0xfe, 0xd2, 0xfb, 0x4d, 0x3c, 0x06, 0x73, 0x1a, 0x09, 0xc6, 0x90, 0x1b, 0x9a, 0x20, 0x1f,
	0x99, 0x71, 0xcd, 0xfd, 0xe6, 0xfe, 0x2a, 0x0e, 0x3e, 0x30, 0x98, 0x5f, 0x64, 0x41, 0xcf, 0xde,
	0x7b, 0x7f, 0x48, 0x65, 0x8c, 0xa0, 0x4c, 0x88, 0x60, 0xa8, 0x44, 0x0e, 0x89, 0x59, 0xd0, 0x50,
	0xea, 0xda, 0x3b, 0x0b, 0x3e, 0xe5, 0x61, 0x3f, 0xcb, 0xba, 0x52, 0x7b, 0xff, 0x48, 0x75, 0x6f,
	0x14, 0x46, 0x62, 0x8a, 0x2a, 0x43, 0x05, 0x8b, 0xca, 0x79, 0x3a, 0xd8, 0x85, 0xa9, 0x3a, 0x23,
	0x5f, 0x0c, 0xe8, 0x09, 0xd5, 0x09, 0x50, 0xc1, 0xa9, 0x89, 0x19, 0x52, 0x85, 0x33, 0x50, 0x37,
	0x96, 0x16, 0x2d, 0xad, 0xa6, 0x95, 0x61, 0x02, 0x97, 0xfc, 0x2a, 0x66, 0x38, 0xb0, 0x71, 0x8a,
	0x4f, 0x48, 0x3d, 0xc7, 0x09, 0x18, 0x3c, 0x1a, 0xf5, 0xbd, 0xa5, 0x95, 0x1d, 0xed, 0x81, 0xc1,
	0x83, 0x61, 0xcf, 0x49, 0xf3, 0x48, 0x72, 0xd4, 0x9a, 0x6a, 0x83, 0x92, 0x86, 0x89, 0x88, 0x26,
	0xba, 0x56, 0xb2, 0xba, 0x7e, 0xa0, 0xd3, 0xca, 0xd0, 0xa0, 0xec, 0xda, 0xc2, 0xe9, 0xcf, 0xfb,
	0xed, 0xb2, 0xd5, 0xdc, 0x2f, 0x72, 0x7e, 0xb8, 0xca, 0xec, 0xd1, 0x1f, 0xb7, 0xcb, 0x96, 0xd3,
	0xfd, 0xff, 0xb4, 0xf6, 0xdd, 0xd5, 0xda, 0x77, 0x5f, 0xd6, 0xbe, 0xfb, 0xb0, 0xf1, 0x9d, 0xd5,
	0xc6, 0x77, 0x9e, 0x37, 0xbe, 0x73, 0xfd, 0xf5, 0x0d, 0x6d, 0x16, 0x12, 0x75, 0x58, 0xb2, 0x3b,
	0xfc, 0xfb, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xd7, 0xe1, 0xf6, 0x2d, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TaskSlaLatenessStepBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TaskSlaLatenessStepBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.TaskSlaLatePenaltyBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TaskSlaLatePenaltyBps))
		i--
		dAtA[i] = 0x28
	}
	if m.TaskSlaOnTimeRewardBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TaskSlaOnTimeRewardBps))
		i--
		dAtA[i] = 0x20
	}
	if m.HeartbeatRecoveryBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HeartbeatRecoveryBps))
		i--
		dAtA[i] = 0x18
	}
	if m.HeartbeatPenaltyBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HeartbeatPenaltyBps))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxCommentLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxCommentLength))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxCommentLength != 0 {
		n += 1 + sovParams(uint64(m.MaxCommentLength))
	}
	if m.HeartbeatPenaltyBps != 0 {
		n += 1 + sovParams(uint64(m.HeartbeatPenaltyBps))
	}
	if m.HeartbeatRecoveryBps != 0 {
		n += 1 + sovParams(uint64(m.HeartbeatRecoveryBps))
	}
	if m.TaskSlaOnTimeRewardBps != 0 {
		n += 1 + sovParams(uint64(m.TaskSlaOnTimeRewardBps))
	}
	if m.TaskSlaLatePenaltyBps != 0 {
		n += 1 + sovParams(uint64(m.TaskSlaLatePenaltyBps))
	}
	if m.TaskSlaLatenessStepBlocks != 0 {
		n += 1 + sovParams(uint64(m.TaskSlaLatenessStepBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCommentLength", wireType)
			}
			m.MaxCommentLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCommentLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatPenaltyBps", wireType)
			}
			m.HeartbeatPenaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartbeatPenaltyBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatRecoveryBps", wireType)
			}
			m.HeartbeatRecoveryBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartbeatRecoveryBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskSlaOnTimeRewardBps", wireType)
			}
			m.TaskSlaOnTimeRewardBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskSlaOnTimeRewardBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskSlaLatePenaltyBps", wireType)
			}
			m.TaskSlaLatePenaltyBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskSlaLatePenaltyBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskSlaLatenessStepBlocks", wireType)
			}
			m.TaskSlaLatenessStepBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskSlaLatenessStepBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
